### ISSUE TITLE
There is no license.

### ISSUE THREAD

**Issue by ghost** [Wolf480pl/PHPass#1]
If you intend this code to be used by other you need to include a license giving others permission to use your software and explaining the terms for use.  Right now the only way anyone can legally use your code is to get written permission from you.  (At least, that's how copyright law works in the US).

Consider including a MIT license with your PHPass implementation; I notice you've use the MIT license on some of your other projects.

**Comment by Wolf480pl** [comment]
Sorry, I wrote it long time ago, and when I was publishing it, forgot to put some license there. I'll put a MIT header there.

**Comment by Wolf480pl** [comment]
Ok, MIT license added.
